spring:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, POST, PUT, DELETE
    allowed-headers: "*"
  application:
    name: user-management
  dataSource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DATABASE_PASSWORD}
#    password: 1234
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
